baseURL = "https://yuvraj.co/"
languageCode = "en-us"
title = "Yuvraj Walia | Personal Website"
disableKinds = ["taxonomyTerm"]


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4